- back/README.md
Modifications générales du README.md se trouvant dans le dossier back:
- Remise en forme générale
- Ajout d'une table des matières
> Update README.md back/

- back/scripts/communities/communities_selector.py
Fix following https://github.com/dataforgoodfr/13_eclaireur_public/pull/31
I think @cgoudet didn't catch this on his machine because the `data/` folder and subdirectories existed from previous runs?
> [BACK] communities: fix processed data folder path

- back/scripts/communities/loaders/odf.py
pushing some minor refactors as I'm digging into code. handling odf.py here.
Mostly just moving logic out of the constructor to get.
I compared the output back/data/communities/processed_data/odf_data.csv between my branch and main and they are identical.
> [BACK] ODF: minor refactor

- back/config.yaml
- back/scripts/loaders/base_loader.py
- back/scripts/loaders/csv_loader.py
- back/scripts/loaders/excel_loader.py
- back/scripts/loaders/json_loader.py
Goals: 
* reduce memory footprint of script when running on local machine.
* reduce execution time to make iterating easier
> [BACK] DevEx: Process small tests file by default

- .github/workflows/pre-commit.yaml
- back/scripts/datasets/datagouv_searcher.py
- Ajoute le système de sauvegarde. La sauvegarde est faite en parquet en local en attendant la convention finale en postgres.
- Retire des doublons dans le dataset final.
> [BACK] Ajoute un système de sauvegarde des appels api de chaque organisation

- back/scripts/datasets/datagouv_searcher.py
- back/scripts/datasets/single_urls_builder.py
- back/scripts/loaders/base_loader.py
- Pure stylistic reformat of SingleURLBuilder
- Use retry mechanism in base loader
> [BACK] Micro reformat SingleURLBuilder

- .gitignore
- back/README.md
- back/config.yaml
- back/scripts/utils/psql_connector.py
- back/scripts/workflow/workflow_manager.py
- docker-compose.yaml
- poetry.lock
- pyproject.toml
- Add local PSQL using docker
- Add missing dependency
- For now, no schemas / migrations management
- Dropping existing table with each export
> [BACK] Simple SQL export

- back/config.yaml
- back/scripts/communities/communities_selector.py
- back/scripts/communities/loaders/odf.py
- back/scripts/communities/loaders/ofgl.py
- back/scripts/communities/loaders/sirene.py
- back/scripts/datasets/datafiles_loader.py
- back/scripts/datasets/datagouv_searcher.py
- back/scripts/datasets/single_urls_builder.py
- back/scripts/utils/geolocator.py
- back/scripts/workflow/workflow_manager.py
Ticket : https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/m6jcs2djf6sm3ee/Taches%20Data%20Back?rowId=30
J'ai refait tourner le pipeline complet sans encombre et aucune bizarrerie n'a été détectée mais pas fait de test "sérieux".
Note au reviewer : à lire par commit pour une bien meilleure lisibilité.
Notes aux devs :
- Certains choix dans l'architecture du `config.yaml` sont discutables et manque de cohérence (les miens ou les précédents), j'ai fait au mieux mais ça pourrait faire l'objet d'un ticket à part si besoin.
- Y'a du `back/data` partout, avec les méthodes `get_project_data_path()` ou `get_project_base_path() / "back" / "data"` on se retrouve avec une logique à deux endroits (c'est quand même bien mieux qu'avant).
> [BACK] feat: move hardcoded paths in config.yaml

- back/config.yaml
Erreur d'inattention qui bloque le pipeline.
> [BACK] fix(pipeline): search.subventions.api.testIds config

- back/scripts/loaders/base_loader.py
- back/scripts/loaders/csv_loader.py
- back/scripts/loaders/excel_loader.py
- poetry.lock
- pyproject.toml
- tests/back/loaders/test_csv_loaders.py
La class CSVLoader sert principalement à trouver les bonnes options pour charger un CSV dans pandas. Une de ses limitations est qu'elle ne s'appliquait qu'aux CSV disponibles via url ou une url du type file:.
Cette PR permet d'appliquer la logique également pour les fichiers déjà sauvegardés sur disque via un Path.
Autre : 
- Reformat général
- utilisation de csv.sinffer pour identifier les délimiters
- Mise en place de TU
- correction d'erreurs d'import lors des TU
> Local csv loader

- back/scripts/utils/datagouv_api.py
- back/scripts/workflow/workflow_manager.py
- tests/back/utils/test_datagouv_api.py
Normalise les description de formats et sélectionne seulement les formats pour lesquelles une extraction est implémentée.
> [BACK] Normalization des descriptions de formats

- back/scripts/datasets/dataset_aggregator.py
- back/scripts/loaders/base_loader.py
- back/scripts/loaders/parquet_loader.py
- tests/back/loaders/fixtures/test_loader_file.txt
- tests/back/loaders/test_base_loader.py
* Création du `BaseLoader._load_from_url` sur la base de `BaseLoader._load_from_file`
* Amélioration de la couverture des tests
* Ajout du catch manquant des erreurs lors du `_process_file`
> [BACK] feat(BaseLoader): split load → _load_from_file + _load_from_url

- .github/workflows/test-run.yaml
- back/config-test.yaml
- tests/back/test_config_structure.py
* Mise à jour de la CI
* Run automatique des tests à chaque PR/push sur main (pour la partie back)
* Correction d'un test
> [BACK] feat: CI run tests

- back/scripts/datasets/datagouv_catalog.py
- back/scripts/datasets/dataset_aggregator.py
- back/scripts/datasets/declaration_interet.py
- back/scripts/datasets/elected_officials.py
- back/scripts/datasets/sirene.py
- back/scripts/workflow/workflow_manager.py
Petite uniformisation des attributs des workflows pour faciliter le futur plug des classes Cleaner.
> [BACK] feat: uniformisation workflow.__init__

- back/scripts/datasets/dataset_aggregator.py
- back/scripts/datasets/marches.py
- back/scripts/utils/datagouv_api.py
Use stable URL to download files. We might consider doing the same for subventions and mutualising logic.
> [BACK] Fix 404s for marches publics

- front/app/api/contact/route.ts
- front/app/community/[siren]/components/FicheHeader/FicheHeader.tsx
- front/app/community/[siren]/page.tsx
- front/app/contact/page.tsx
- front/app/page.tsx
- front/components/ContactForm.tsx
- front/components/ProjectDescription.tsx
- front/components/ui/badge.tsx
- front/components/ui/dropdown-menu.tsx
- front/components/ui/switch.tsx
- front/components/ui/table.tsx
- front/components/ui/tabs.tsx
- front/utils/send-email.ts
- front/utils/utils.ts
Juste la partie front pour l'instant, les chiffres clés à afficher n'ont pas l'air encore clairs.
> feat: Ajout du composant ProjectDescription à la page d'accueil

- back/scripts/communities/communities_selector.py
- back/scripts/datasets/ofgl_urls.csv
- back/scripts/utils/geolocator.py
Ajoute les champs latitude et longitude aux collectivités. Le taux de remplissage n'est pas optimal mais fera l'object d'un ticket séparé. L'objectif est de créer la structure finale nécessaire au web.
> [BACK] Ajoute latitude/longitude aux collectivités

- front/app/api/selected_communities/route.ts
- front/utils/fetchers/communities/createSQLQueryParams.ts
- front/utils/fetchers/communities/fetchCommunities-client.ts
- front/utils/fetchers/functions/stringifySelectors.ts
- front/utils/fetchers/marches-publics/createSQLQueryParams.ts
- front/utils/fetchers/subventions/createSQLQueryParams.ts
Add new interface to fetchers (subventions, MP, communities)  :
* filters (where clauses)
* selectors (columns to get)
* limit (max number of items)
> [FRONT] feature: improve fetchers 

- front/app/community/[siren]/components/FicheMarchesPublics/FicheMarchesPublics.tsx
- front/app/community/[siren]/components/FicheMarchesPublics/Trends.tsx
- front/app/map/page.tsx
J ai fix un probleme qui est passe entre les mailles du filet quand j ai change les params des hooks d api et nettoyer un peu le code.
> [FRONT] fix: api hooks (filters and limit)

- back/scripts/enrichment/marches_enricher.py
Nettoyage de la colonne du type identifiant titulaire
> [BACK] MP enricher type identifiant du titulaire

- back/scripts/enrichment/marches_enricher.py
Traitement des dernières colonnes json considerationsEnvironnementales, modaliteExecution, technique et modification du traitement de typesPrix qui était très similaire
> [BACK] MP enricher considerationsEnvironnementales, modaliteExecution, technique

- front/app/models/subvention.ts
Mettre à jour les propriétés de la table subvention pour matcher avec la table en base
> [FRONT] Update Subvention properties to match db

- front/app/community/[siren]/components/NeighboursMap/MapWithCityMarkers.tsx
Bloque l interaction avec la carte des voisins dans la fiche collectivite.
Ticket : https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/mpl5qhhyydqkc5v?rowId=1
> [FRONT] fix: block map interaction for neighbours map 

- front/app/community/[siren]/components/CommunityDetails.tsx
- front/app/community/[siren]/components/FicheMarchesPublics/MarchesPublicsTrendsBarChart.tsx
- front/components/SearchBar/SearchBar.tsx
- front/utils/utils.ts
This PR fixes the following points:
- Inhabitants and public agents are now integers instead of floating-point numbers.
- Rewrote the sentence placeholder for the search bar.
Tickets:
https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/mpl5qhhyydqkc5v?rowId=20
https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/mpl5qhhyydqkc5v?rowId=21
> [FRONT] Fix : No more chopping humans into pieces — Make Humans Whole Again ;)

- front/app/community/[siren]/components/DownloadDataButton.tsx
- front/app/community/[siren]/components/FicheMarchesPublics/Contracts.tsx
- front/app/community/[siren]/components/FicheSubventions/Ranking.tsx
Ticket : 
https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/mpl5qhhyydqkc5v?rowId=13
> [FRONT] Fix : Remove dropdown menu from ranking download button

- front/components/Pagination/Pagination.tsx
This PR hides the pagination when there is only one page
Ticket : 
https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/mpl5qhhyydqkc5v?rowId=14
> [FRONT] Fix : Make pagination invisible for one page

- .pre-commit-config.yaml
- back/main.py
- back/scripts/communities/loaders/sirene.py
- back/scripts/datasets/cpv_labels.py
- back/scripts/enrichment/bareme_enricher.py
- back/scripts/enrichment/base_enricher.py
- back/scripts/enrichment/communities_enricher.py
- back/scripts/enrichment/financial_account_enricher.py
- back/scripts/enrichment/marches_enricher.py
- back/scripts/enrichment/utils/cpv_utils.py
- back/tests/select_test_citites.py
- pyproject.toml
- tests/back/datasets/test_marches.py
Mise à jour de la config de ruff. Ajout du tri des imports. Mise à jour du pre-commit.
> [BACK] feat: upgrade ruff python version, ruff-pre-commit, add isort config

- back/scripts/workflow/workflow_manager.py
Prévention contre la modification de la config entre Workflow.
> [BACK] feat: protect config between Workflow

- back/scripts/loaders/base_loader.py
- back/scripts/loaders/csv_loader.py
- back/scripts/loaders/excel_loader.py
- back/scripts/loaders/json_loader.py
- back/scripts/loaders/parquet_loader.py
- back/scripts/loaders/xml_loader.py
- tests/back/loaders/test_base_loader.py
- Refactorisation de `CSVLoader` et `XMLLoader`
- Optimisation de `JsonLoader`
- Meilleure abstraction des méthodes `__init__`
- Uniformisation de l'utilisation de `LOGGER`
- Ajout de messages logging
- Ajout de typing
- Ajout/Mise à jour de quelques docstrings
> [BACK] feat: revue Loader

- front/app/community/[siren]/components/FicheMarchesPublics/MarchesPublicsTrendsBarChart.tsx
- front/app/community/[siren]/components/FicheMarchesPublics/Trends.tsx
- front/app/community/[siren]/components/FicheSubventions/Evolution.tsx
Cette PR standardise  les graphiques d'évolution des Marchés Publics : 
- Affichage des huit dernières années
- Label "Aucunes données publiées" pour les années sans données
Ticket Noco : 
https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/m66doartfgeatkv/vw07ogj1b4xcen02?rowId=100
> [FRONT] Fix : Standardisation graphiques évolution des Marchés Publics

- back/scripts/datasets/dataset_aggregator.py
- back/scripts/datasets/utils.py
- back/scripts/utils/decorators.py
This PR:
- adds docstrings to the following classes: BaseDataset, DatasetAggregator
- adds docstrings and type hints to the tracker() decorator factory
This is part of my effort to verify my understanding of this part of the codebase
> [BACK] chore: add docstring and type hints

- back/scripts/communities/communities_selector.py
* Fix du retour de add_geo_and_postal_metrics si le fichier existe déjà
* Ajout de `@tracker` sur les méthodes add_epci_infos et add_geocoordinates
> [BACK] fix: CommunitiesSelector.add_geo_and_postal_metrics

- back/scripts/datasets/dataset_aggregator.py
- back/scripts/datasets/single_urls_builder.py
- back/scripts/datasets/utils.py
- back/scripts/loaders/excel_loader.py
- back/scripts/utils/dataframe_operation.py
- back/scripts/workflow/workflow_manager.py
- tests/back/utils/test_dataframe_operations.py
* Retrait de quelques bourdes sur lors du DatasetAggregator
* Remise au goût du jour de SingleUrlsBuilder
* Élargissement des extensions des fichiers subventions téléchargés (une centaine de fichier concernés, tous ne sont pas lus avec succès mais pourraient le devenir sans trop forcer, cf ligne en-dessous)
* Élargissement des extensions gérées par ExcelLoader
* Ajout de typing
Plus bas, quelques commentaires précisent les choix.
> [BACK] revue subventions

- back/scripts/enrichment/subventions_enricher.py
Migrate subventions_enricher to polars LazyFrame.
Seems to do the trick.
See : https://docs.pola.rs/user-guide/lazy/using/
> fix(subventions-enricher): migrate to pl.LazyFrame

- back/scripts/enrichment/bareme_enricher.py
- back/scripts/enrichment/base_enricher.py
- back/scripts/enrichment/communities_enricher.py
- back/scripts/enrichment/elected_officials_enricher.py
- back/scripts/enrichment/financial_account_enricher.py
- back/scripts/enrichment/marches_enricher.py
- back/scripts/enrichment/subventions_enricher.py
- back/scripts/workflow/data_warehouse.py
Quelques retouches pour les enrichments.
- remplacement des typing.List → list
- retour sans download si le fichier output existe déjà
- ajout minimal de log
- refacto de `__init__`
- renommage `_config` → `config` pour coller au reste du projet
- rajout d'un classmethod oublié
> [BACK] chore: Enrichment

- front/tailwind.config.ts
Fixes dataforgoodfr/13_eclaireur_public#331
> [FRONT] feat/semantic-style

- front/app/advanced-search/components/AdvancedSearchDataTable.tsx
- front/app/advanced-search/components/AdvancedSearchPageContent.tsx
- front/app/advanced-search/components/DownloadingButton.tsx
- front/app/advanced-search/components/Filters/PopulationSliderFilter.tsx
- front/app/advanced-search/components/Filters/Selector.tsx
- front/app/advanced-search/page.tsx
- design plus responsive (scroll x)
- plus d'espace
- colonne mieux définie en version mobile
> [FRONT] table advanced search visualisation

- .github/workflows/review.yml
Updates CleverCloud review app configuration
> Fix: Update CleverCloud review app configuration

- front/app/community/[siren]/components/FicheMarchesPublics/MarchesPublicsSectorTreeMap.tsx
- front/app/community/[siren]/components/FicheSubventions/SubventionsSectorTreemap.tsx
- front/components/DataViz/Treemap.stories.tsx
- front/components/DataViz/Treemap.tsx
http://eclaireurpublic.fr/community/213105554?mp=distribution
> [FRONT] ajout zoom arrière.

- front/app/(comprendre)/contexte/page.tsx
- front/app/(comprendre)/methodologie/page.tsx
- front/app/components/SectionHeader.tsx
- front/app/license/page.tsx
Cette PR : 
- Mets à jour la page Licence
- Modifie le composant SectionHeader pour qu'il soit utilisable sur toutes les pages (contenu React.node), responsive et conforme au Figma
ticket : https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/m66doartfgeatkv/vw3pb5gbfxlzunet?rowId=209
> [FRONT] : Refactor Licence

- front/app/(a-propos)/le-projet/page.tsx
- front/app/components/SectionHeader.tsx
- front/app/legal/page.tsx
Cette PR refactore les pages : 
- Mentions légales
- Le projet
Tickets : 
https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/m66doartfgeatkv/vw3pb5gbfxlzunet?rowId=207
https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/m66doartfgeatkv/vw3pb5gbfxlzunet?rowId=210
> [FRONT] - Refactor - Mentions légales & Le projet

- front/components/ErrorPage.tsx
US-0239
https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/m66doartfgeatkv/vww3ti7zug10c8e3?rowId=239
> [FRONT] - Fix - Centrage Vertical des messages d'erreurs pour petits écrans
