dataforgoodfr/13_eclaireur_public

- back/README.md
- back/scripts/utils/argument_parser.py
Une simplification de l'argument "filename" qui prend comme valeur par défaut ./config.yaml    .
- Lancer le script ne requiert plus de préciser l'emplacement de config.yaml s'il se trouve à la racine du script.
- Il est possible de charger une autre config en utilisant l'arugment ainsi: --filename <chemin_ver_sconfig.yaml>
- Une docstring help permet de comprendre l'argument à l'appel du script.
- La partie 'Lancer le script' du REAMD.md dans back/ est mise à jour en conséquence.
Msg commit:
- Changed arg filename to --filename
- --filename no longer required to execute the main.py script (now has ./config.yaml as default value)
- Added help docstring for the arg
Updated README.md (back/README.md) consequently -> "Lancer le script" chapter
> [BACK] Argument parser minor update

- back/README.md
- back/config.yaml
- back/scripts/utils/argument_parser.py
- Correction config.yaml évitant le soucis de chemins relatifs
- Correctif argument_parser.py : L'arg désignant config.yaml possède un chemin par défaut relatif partant également de la racine du repo.
- Script à lancer depuis racine du projet: ./back/main.py
> [BACK] correction config yaml

- back/scripts/workflow/workflow_manager.py
Goal: reduce memory footprint of the script, as devs with 8GB of RAM on their machines are hitting OOM errors (see [Slack](https://data-for-good.slack.com/archives/C08AW9JJ93P/p1739257564258069))
Before: the script keeps all final datasets in memory in order to later save them to SQL, even when saving to SQL is disabled by config.
After: the script keeps final datasets in memory only if saving to SQL is enabled in config.
> [BACK] workflow_manager: keep normalized data in memory only when persisting to SQL

- back/scripts/communities/communities_selector.py
- back/scripts/datasets/datafiles_loader.py
- back/scripts/datasets/datagouv_searcher.py
- back/scripts/datasets/single_urls_builder.py
- back/scripts/utils/config.py
- back/scripts/utils/geolocator.py
- back/scripts/workflow/workflow_manager.py
Depuis la PR https://github.com/dataforgoodfr/13_eclaireur_public/pull/36/, dans `CommunitiesSelector.__init__` on a un path incorrect : 
`get_project_base_path() / "data" / "datagouv_search"`.
Ça pose problème lors de l'exécution du `main.py`. J'ai vu la review mais pas le fix correspondant.
J'en ai profité pour refactoriser en créant `get_project_data_path` pour éviter que cette erreur ne se reproduise.
Si c'est ok pour vous sur le principe, je peux aussi refactoriser le contenu du fichier `config.yaml` et ses appels de façon à pouvoir (ou pas) déplacer ce dossier `data/` sans encombre.
> [BACK] Fix CommunitiesSelector data path + refacto

- back/scripts/datasets/datagouv_searcher.py
Un PR précédente ne gardait qu'un seul dataset par dataset_id. Or dataset_id représente une page data.gouv et peut contenir plusieurs fichier différents : des années différentes par exemple.
Retire la condition d'unicité sur dataset_id.
> Correction bug perte de dataset

- .gitignore
- back/config-test.yaml
- back/config.yaml
- back/main.py
- back/scripts/datasets/datagouv_searcher.py
- back/scripts/utils/datagouv_api.py
- back/scripts/utils/elected_officials.py
- back/scripts/utils/politiques_elus.py
- back/scripts/workflow/workflow_manager.py
https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/m6jcs2djf6sm3ee/Vue%20publique?rowId=36
- Chaque resource de ce dataset contient un type d'élu différent (maire, sénateur, député, ...)
- La page du dataset permet d'obtenir tous les liens des différents resources, qui sont alors individuellement téléchargés et transformées en parquet.
- Les différents datasets sont finalement combinés en un unique dataset.
- L'interaction avec l'API data.gouv a été reformat pour réutiliser la logique de datagouvsearcher dans EluWorflow.
> [BACK] Ajoute le dataset des élus

- .github/workflows/review.yml
- front/app/api/selected_communities/route.ts
- front/app/community/[siren]/page.tsx
- front/utils/fetchers/fetchCommunities.ts
- front/utils/fetchers/fetchCommunityBySiren.ts
Changements effectués
Cette PR ajoute la possibilité de filtrer les communautés par numéro SIREN dans notre API REST et affiche les détails d'une communauté spécifique.
1. Modifications de l'API (route.ts)
Ajout du paramètre optionnel siren dans les options de filtrage
Mise à jour de la construction des requêtes SQL pour permettre le filtrage par SIREN seul ou combiné avec un type
Amélioration de la génération dynamique des conditions WHERE pour supporter des filtres multiples
Validation du format SIREN (9 chiffres) côté serveur
2. Création de la page de détail d'une communauté
Ajout d'une interface Community qui type correctement les données
Récupération des données de communauté en fonction du SIREN fourni dans les paramètres
Affichage formaté des informations principales (nom, SIREN, …
> [FRONT] Ajout du filtrage par SIREN dans l'API des communautés

- back/tests/config_structure_test.py
- tests/back/test_config_structure.py
Depuis https://github.com/dataforgoodfr/13_eclaireur_public/pull/57, on sait qu'une simple manipulation dans le fichier config peut tout faire sauter 🧨
Voici un test qui fait quelques vérifications, notamment sur les types des données.
Comme il n'y a pas de structure clairement définie (pas assez stable à l'heure actuelle), on compare et on révèle les différences des fichiers config de façon récursive.
Comme cela n'aurait pas suffit à déceler l'erreur à l'origine de la PR citée plus haut, un check supplémentaire est réalisé pour savoir si des configurations secondaires posséderaient une ou plusieurs clés que n'auraient pas la config de base. On aurait alors remarqué que la clé `testIds` était absente de là où elle aurait dû être (mais pas vu qu'elle était au mauvais endroit).
C'est bien …
> [BACK] feat: test sur la structure des config.yaml

- back/scripts/loaders/__init__.py
- back/scripts/loaders/base_loader.py
- back/scripts/loaders/csv_loader.py
- back/scripts/loaders/excel_loader.py
- back/scripts/loaders/json_loader.py
- back/scripts/loaders/parquet_loader.py
- tests/back/loaders/test_base_loader.py
- tests/back/loaders/test_csv_loaders.py
* ajout des attributs `file_extensions` et `media_type_regex` à `BaseLoader` qui permettent de définir dans chacune des classes enfants, quelles extensions de fichier est attendue (plutôt que faire un gros pâté dans BaseLoader)
* `media_type_regex` sert pour faire correspondre les content-type des fichiers téléchargés (cette fonctionnalité était mise en place pour les fichiers excel, c'est désormais étendu à toutes les classes par défaut, suffit de la mettre à None pour le désactiver (valeur par défaut))
* split de la méthode `BaseLoader.loader_factory` afin de pouvoir surcharger les méthodes dans chacune des classes, retrait des imports directement dans la méthode
* gestion minimale du status code des requêtes pour déterminer le "content-type" du fichier téléchargé
* …
> [BACK] feat: revue BaseLoader

- back/main.py
- back/scripts/datasets/dataset_aggregator.py
- back/scripts/datasets/declaration_interet.py
- back/scripts/datasets/elected_officials.py
- back/scripts/datasets/sirene.py
- back/scripts/workflow/data_warehouse.py
- back/scripts/workflow/workflow_manager.py
Les méthodes `run` renvoient parfois `None`, parfois `self`. Cela complique le code, sa maintenance et est source d'erreur.
Dans la majorité des cas, le run renvoie `None`, c'est donc ce choix qui a été retenu.
Des exemples de situations que cette PR cherche à simplifier :
```py
data_warehouse_manager = DataWarehouseWorkflow(config).run()
```
`data_warehouse_manager` vaut None.
```py
ElectedOfficialsWorkflow(self.config["elected_officials"]["data_folder"]).run()
SireneWorkflow(self.config["sirene"]).run()
```
`ElectedOfficialsWorkflow.run()` renvoie self
`SireneWorkflow.run()` renvoie None
```py
DatasetAggregator.run()
```
Renvoie self, mais sa signature indique qu'il renvoie None.
> [BACK] chore: run methods return None

- back/main.py
- back/scripts/utils/config.py
Parfois on a besoin d'accéder à la configuration du projet comme dans `LoggerManager` ou `DataWarehouseWorkflow`.
Actuellement, on fourni le fichier config à toutes les classes qui en auraient potentiellement besoin. Et parfois, pas de la plus belle des façons.
Le problème c'est que l'on ne sait pas encore quel fichier config va être utilisé lors du chargement des fichiers python.
Cette PR vise à contourner le problème en permettant d'accéder simplement au fichier configuration chargé n'importe où dans le projet une fois le script `main` activé.
```py
from back.scripts.utils.config import project_config
project_config["workflow]["save_to_db"]
project_config.workflow["save_to_db"]
```
> [BACK] feat: add project_config

- back/config-test.yaml
- back/config.yaml
- back/scripts/communities/communities_selector.py
- back/scripts/communities/loaders/ofgl.py
- back/scripts/datasets/communities_financial_accounts.py
- back/scripts/datasets/datagouv_catalog.py
- back/scripts/datasets/dataset_aggregator.py
- back/scripts/datasets/declaration_interet.py
- back/scripts/datasets/elected_officials.py
- back/scripts/datasets/marches.py
- back/scripts/datasets/sirene.py
- back/scripts/datasets/topic_aggregator.py
- back/scripts/enrichment/base_enricher.py
- back/scripts/enrichment/communities_enricher.py
- back/scripts/enrichment/marches_enricher.py
- back/scripts/enrichment/subventions_enricher.py
- back/scripts/utils/config.py
- back/scripts/workflow/data_warehouse.py
- back/scripts/workflow/workflow_manager.py
* Added a package aiming to contain clean and enrichment code
* Move subventions enrichment into it's own logic
* Send marches and communities to PSQL again
* Each workflow step now specifies it's config key and output path, to make it easier to plug into a previous step, and prepare for a functional template
> [BACK] Add template for enrichers + resend data to PSQL

- back/scripts/datasets/marches.py
- tests/back/datasets/fixtures/marche_direct.json
- tests/back/datasets/fixtures/marche_nested.json
- tests/back/datasets/test_marches.py
Added heuristics to handle different structures in .json marches publics
- Cases where "titulaires" are nested
- Cases where "acheteur" is a dict contaning "id" (being either str or int) vs when "acheteur.id" is a field 
- -> returning systematically "acheteur.id" as a string
- Identifying columns that are unnecessarilly nested (only contains a single declaration with similar header). Not used so far
> [BACK] Adding heuristics to handle different .json structures

- back/config-test.yaml
- back/config.yaml
- back/scripts/communities/communities_selector.py
Limite les colonnes ajoutées par code_postal et geo metrics au minimum demandé. Evite d'avoir deux fois la colonne population.
> [BACK] Corrige les doubles colonnes population

- front/components/ProjectDescription.tsx
- front/utils/fetchers/constants.ts
- front/utils/fetchers/kpis/fetchCommunitiesTotalCount.ts
- front/utils/fetchers/kpis/fetchPublishedSubventionsTotal.ts
- front/utils/fetchers/kpis/fetchPusblishedMarchesPublicsTotal.ts
- front/utils/fetchers/kpis/fetchSubventionsTotalBudget.ts
PR pour les requetes qui etaient possible defaire avec les tables actuelles dans le back ! (donc Nombre de collectivités étudiées Montant total subventions déclarées de manière exploitable, Montant total subventions dans budget) la partie MP, les clefs ne sont pas encore en snake_case
> [FRONT] feature: add fetchers and kpis for total communities count and subventions

- front/app/(a-propos)/faq/page.tsx
- front/app/components/KPIs.tsx
This PR fixes : 
- The word "Footer" in the FAQ, unknown for most people. Changed for "bas de page"
- Homepage, project section : collectivité number as integer
Tickets : 
https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/mpl5qhhyydqkc5v?rowId=26
https://noco.services.dataforgood.fr/dashboard/#/nc/p6lbzxq9ra31no8/mpl5qhhyydqkc5v?rowId=27
> [FRONT] : Fix : FAQ footer word changed + Homepage collectivités number as integer

- .github/workflows/run-main.yaml
- back/scripts/workflow/workflow_manager.py
Action qui exécute quotidiennement le script `main.py`. Le script peut être lancé manuellement.
Ça serait bien qu'il crée une alerte s'il échoue, mais il y a d'autres priorités :
Actuellement, le script ne va pas jusqu'au bout : le processus est kill lors du `OfglLoader` (téléchargement de plusieurs Go de données ou/et traitements des fichiers).
C'est un problème car ce fichier est nécessaire pour de nombreux workflows.
Entre nous, en local, mon ordinateur capitule au même endroit.
J'ai créé un ticket (P0).
L'ordre d'exécution des workflows a été un peu modifié.
L'objectif - à défaut de faire fonctionner le process jusqu'au bout - est qu'il échoue le plus tard possible : tous les workflows qui ne dépendent pas de `OfglLoader` ont donc été placés avant celui-ci.
Le changement d'ordre des …
> [BACK] Ajout d'un tâche CRON github action

- front/app/community/[siren]/components/FicheSubventions/SubventionYearlyAmountsChart.tsx
- front/app/community/[siren]/components/FicheSubventions/SubventionYearlyCountsChart.tsx
Cette PR standardise les graphiques d'évolution des subventions selon les modalités suivantes : 
- Affichage des 8 dernières années
- Pour les années sans données, un message "Aucunes données publiées" apparait sur les années en question
> [FRONT] : fix : Standardisation des graphs pour les subventions

- back/scripts/workflow/workflow_manager.py
Un workflow qui plante ne devrait pas, par défaut, bloquer l'exécution des suivants.
> [BACK] feat(WorkflowManager): exception catch added 

- back/scripts/communities/loaders/ofgl.py
- back/scripts/datasets/communities_financial_accounts.py
- back/scripts/datasets/dataset_aggregator.py
- back/scripts/loaders/zip_loader.py
Utiliser directement `LOADER_CLASSES` est tentant mais c'est `BaseLoader` qui contient la logique de son utilisation.
> [BACK] chore: privileged use of BaseLoader instead of LOADER_CLASSES

- back/scripts/loaders/base_loader.py
- back/scripts/loaders/csv_loader.py
- back/scripts/loaders/excel_loader.py
- back/scripts/loaders/json_loader.py
- back/scripts/loaders/parquet_loader.py
- back/scripts/loaders/xml_loader.py
- back/scripts/loaders/zip_loader.py
L'objectif de cette PR est de flexibiliser l'utilisation des Loader en permettant de définir tous les paramètres nécessaires pour charger les fichiers lors de son initialisation.
Actuellement, on gère spécifiquement le `dtype`, parfois `columns`.
Dans Geolocator, on aurait besoin de `decimal` par exemple et il faudrait donc définir ce cas unitairement. Autant généraliser ça.
Les attributs sont fournis lors de l'initialisation du Loader `CSVLoader(file_url, sep=";", dtype={"siren": str}, …)`, ces attributs sont appelés lors du chargement du fichier.
`get_loader_kwargs` permet de pouvoir surcharger plus finement les attributs fournis lors du init (voir `CsvLoader` pour l'exemple).
L'utilisation de `get_loader_kwargs` a été généralisé à tous les loaders.
> [BACK] feat: add LoaderBase.get_loader_kwargs

- back/scripts/datasets/ofgl_urls.csv
Cette PR permet de ne télécharger que les champs utiles du workflow Ofgl plutôt que tout télécharger pour ensuite les filtrer.
Cela permet de réduire fortement la taille des fichiers et l'impact sur le CPU lors de leur lecture.
La qualité des résultats ne devrait pas être impactée.
> [BACK] feat(OFGL): ajout filtre avant téléchargement

- back/scripts/datasets/datagouv_catalog.py
- back/scripts/loaders/base_loader.py
Le catalogue DataGouv se met à jour quotidiennement, avec un id et un nom imprévisibles.
Problème n°1 :
Actuellement l'id est fixé en dur dans le code : on travaille avec un catalogue du mois de mars.
Problème n°2 :
Le fichier csv fait 787Mo, c'est long à télécharger et trop lourd pour pandas qui réclame trop de ressources pour le lire. Le CRON github plante lors de cette étape.
Cette PR propose d'aller chercher automatiquement la dernière url du catalogue en date et de télécharger sa version parquet (128Mo) qui réduit très fortement les problématiques de téléchargement et de pandas.
> [BACK] feat: DataGouvCatalog optimisation

- back/scripts/communities/loaders/ofgl.py
Un code insee `02` est lu `2` suite au passage de OFGL en 2024 car je n'ai pas forcé le type à `str` à la lecture dans [cette PR](https://github.com/dataforgoodfr/13_eclaireur_public/pull/307)
> [BACK] Fix/ofgl 2024

- front/app/(visualiser)/interpeller/[siren]/step1/page.tsx
- front/app/community/[siren]/components/FicheMarchesPublics/FicheMarchesPublics.tsx
- front/app/community/[siren]/page.tsx
- front/app/models/bareme.ts
- front/app/models/community.ts
- front/utils/fetchers/communities/fetchTransparencyScore-server.ts
Les scores de transparences actuels sont dans la table collectivités (et correspondent à 2023 de la table bareme). Chloé va apporter une modification pour rajouter une colonne dans cette table pour la tendance afin de fetcher à un seul endroit.
Le score agrégé est déjà calculé par le back, pas besoin de le recalculer au front mais juste de le fetch
> [FRONT] Fix - Fetch TransparencyScore from Communities Table + fetch Aggregated Score 
